"""initial_uptc_infrastructure

Revision ID: 9e83f63789f1
Revises: 
Create Date: 2026-01-30 14:13:40.266650

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9e83f63789f1'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=50), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('full_name', sa.String(length=120), nullable=True),
    sa.Column('hashed_password', sa.String(length=128), nullable=False),
    sa.Column('user_type', sa.String(length=20), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_email'), ['email'], unique=True)
        batch_op.create_index(batch_op.f('ix_users_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_users_username'), ['username'], unique=True)

    op.create_table('campuses',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('location_city', sa.String(length=100), nullable=True),
    sa.Column('population_students', sa.Integer(), nullable=True),
    sa.Column('population_staff', sa.Integer(), nullable=True),
    sa.Column('total_area_sqm', sa.Float(), nullable=True),
    sa.Column('primary_usage', sa.String(length=100), nullable=True),
    sa.Column('baseline_energy_kwh', sa.Float(), nullable=True),
    sa.Column('target_reduction_percent', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint('population_students >= 0', name='check_pos_students'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('campuses', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_campuses_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_campuses_user_id'), ['user_id'], unique=False)

    op.create_table('consumption_records',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('campus_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('reading_value', sa.Float(), nullable=False),
    sa.Column('reading_date', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('resource_type', sa.String(length=20), nullable=True),
    sa.Column('source', sa.String(length=50), nullable=True),
    sa.CheckConstraint('reading_value >= 0', name='check_pos_reading'),
    sa.ForeignKeyConstraint(['campus_id'], ['campuses.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('consumption_records', schema=None) as batch_op:
        batch_op.create_index('ix_consumption_campus_date', ['campus_id', 'reading_date'], unique=False)
        batch_op.create_index(batch_op.f('ix_consumption_records_campus_id'), ['campus_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_consumption_records_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_consumption_records_user_id'), ['user_id'], unique=False)

    op.create_table('infrastructure_units',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('campus_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('unit_type', sa.String(length=50), nullable=True),
    sa.Column('area_sqm', sa.Float(), nullable=True),
    sa.Column('is_critical', sa.Boolean(), nullable=True),
    sa.Column('avg_daily_consumption', sa.Float(), nullable=True),
    sa.Column('peak_hours', sa.String(length=100), nullable=True),
    sa.Column('status', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['campus_id'], ['campuses.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('infrastructure_units', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_infrastructure_units_campus_id'), ['campus_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_infrastructure_units_id'), ['id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('infrastructure_units', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_infrastructure_units_id'))
        batch_op.drop_index(batch_op.f('ix_infrastructure_units_campus_id'))

    op.drop_table('infrastructure_units')
    with op.batch_alter_table('consumption_records', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_consumption_records_user_id'))
        batch_op.drop_index(batch_op.f('ix_consumption_records_id'))
        batch_op.drop_index(batch_op.f('ix_consumption_records_campus_id'))
        batch_op.drop_index('ix_consumption_campus_date')

    op.drop_table('consumption_records')
    with op.batch_alter_table('campuses', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_campuses_user_id'))
        batch_op.drop_index(batch_op.f('ix_campuses_id'))

    op.drop_table('campuses')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_username'))
        batch_op.drop_index(batch_op.f('ix_users_id'))
        batch_op.drop_index(batch_op.f('ix_users_email'))

    op.drop_table('users')
    # ### end Alembic commands ###
